### ISSUE TITLE
EVK Ruuvi tags

### ISSUE THREAD

**Issue by JJanAA** [wirepas/evk#3]
Got the EVK up working, but the Ruuvi tags ran out of battery after a few days (2-5 days). What is the expected lifetime of batteries in the Ruuvi tags configured for WM?

**Comment by PFigs** [comment]
Hi!

Thanks for reaching out and raising an issue!

I kindly ask you to reach out to a sales representative in order to get our power consumption estimates for NRF52 based devices.

The consumption you see is certainly abnormal and we will investigate on what could be the root cause. 

Could you also forward your gateway logs to opensource@wirepas.com along with the demonstration server you are connecting to?

Have a good day!

**Comment by JJanAA** [comment]
Thank you! 
Where do I find the gateway logs?

**Comment by PFigs** [comment]
You're welcome :smile: 

Please find the logs from the Raspberry Pi. 

Please refer to [this link for step by step instructions on how to access your device](https://github.com/wirepas/evk/blob/master/evk/kit_ruuvi.rst#setting-up-the-gateway-software).

**Comment by JJanAA** [comment]
Do you have the name on the log file to look for?

**Comment by PFigs** [comment]
Check the running containers and status with:

> docker ps -a

Please collect the information and send it to us as well.

After that, please provide a dump of each container you have running with

> docker logs <container name>  >& <container_name>.log

**Comment by PFigs** [comment]
Hi,

I took a few nodes from the same production batch and they have been operating for over 2 weeks.

**Comment by JJanAA** [comment]
The nodes seems to work fine with new batteries. I guess we got some bad batteries in the start. Ok now.
